
package com.wjl.test0.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceTest", targetNamespace = "http://test0.wjl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceTest {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handler", targetNamespace = "http://test0.wjl.com/", className = "com.wjl.test0.Handler")
    @ResponseWrapper(localName = "handlerResponse", targetNamespace = "http://test0.wjl.com/", className = "com.wjl.test0.HandlerResponse")
    @Action(input = "http://test0.wjl.com/ServiceTest/handlerRequest", output = "http://test0.wjl.com/ServiceTest/handlerResponse")
    public String handler(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
